### ISSUE TITLE
关于框架实现的一些问题

### ISSUE THREAD

**Issue by unihon** [sparrow-js/sparrow#10]
目前还在探索阶段，想请教下关于web页面的拖拽预览的实现原理是怎样的，特别是组件的嵌套，预览代码和最终生产代码是如何分离的。

**Comment by sparrow-js** [comment]
> 目前还在探索阶段，想请教下关于web页面的拖拽预览的实现原理是怎样的，特别是组件的嵌套，预览代码和最终生产代码是如何分离的。

有很多种不同的实现思路，底层都是处理数据，简单说下原理：
1. 拖拽预览：sortablejs 生成数据
2.嵌套：递归组件树
3.预览代码和最终生产代码分离：这个项目预览和生产代码都是编译阶段直接输出的代码，通过状态在组件内部区分输出代码

**Comment by unihon** [comment]
都回答了，谢谢
