### ISSUE TITLE
小小使用后的感受

### ISSUE THREAD

**Issue by Yangjia23** [sparrow-js/sparrow#16]
1、希望支持拖拽功能
2、希望可以设置高度、宽度，同时高亮的时候，可以显示高度区域的高度和宽度
3、希望已选组件右击可删除，或者右上角有个删除按钮，而不是需要到属性里面去删除
希望对你有帮助

**Comment by sparrow-js** [comment]
好的，意见会参考的

**Comment by sparrow-js** [comment]
> 1、希望支持拖拽功能
> 2、希望可以设置高度、宽度，同时高亮的时候，可以显示高度区域的高度和宽度
> 3、希望已选组件右击可删除，或者右上角有个删除按钮，而不是需要到属性里面去删除
> 希望对你有帮助

好的，建议会参考的
