### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by lusoftware** [sparrow-js/sparrow#18]
### 问题
安装到本地，启动后，具体如何使用？是否能提供一个在线demo？
### 环境
- ubuntu 16.04
- node v12.19.0
- chrome 86
### 操作步骤
1. 全局安装并启动
2. 打开页面
3. 点击/拖拽添加组件到内容区域
![Peek 2020-11-04 13-20](https://user-images.githubusercontent.com/25131081/98072277-9cd90100-1ea0-11eb-8970-cde01e9ac213.gif)
### 结果
1. 无法添加组件
2. 切换左侧侧边栏时控制台报错
![image](https://user-images.githubusercontent.com/25131081/98072501-24267480-1ea1-11eb-897b-9d197f3d4920.png)
![image](https://user-images.githubusercontent.com/25131081/98072372-d9a4f800-1ea0-11eb-83cb-3ef4d1a2ee09.png)
终端 log如下
![image](https://user-images.githubusercontent.com/25131081/98072795-d3fbe200-1ea1-11eb-98d8-bfb4c54564cb.png)

**Comment by sparrow-js** [comment]
目前只能在本地电脑上用，online版开发中，后续会开源出来

**Comment by lusoftware** [comment]
并没有被占用，重启没有解决问题

**Comment by sparrow-js** [comment]
> 并没有被占用，重启没有解决问题

怎么访问的，你那有没有mac或者win的电脑试试

**Comment by lusoftware** [comment]
> > 并没有被占用，重启没有解决问题
> 
> 怎么访问的，你那有没有mac或者win的电脑试试

全局安装，自动打开的8000，mac上可以使用
