### ISSUE TITLE
请问项目生成源码以后，是通过什么途径修改到view工程的源代码中的

### ISSUE THREAD

**Issue by tgly307** [sparrow-js/sparrow#19]
修改了组件以后由client触发了socket操作，服务端生成源代码以后修改view中的源代码，这一步是通过什么途径实现的？

**Comment by sparrow-js** [comment]
> 修改了组件以后由client触发了socket操作，服务端生成源代码以后修改view中的源代码，这一步是通过什么途径实现的？

写文件
