### ISSUE TITLE
依赖下载完整，editor-box代码编辑区域无法展示

### ISSUE THREAD

**Issue by jtfl2008** [sparrow-js/sparrow#2]
iframe框架  localhost 拒绝了我们的连接请求

**Comment by sparrow-js** [comment]
> iframe框架 localhost 拒绝了我们的连接请求

localhost  改成 http://127.0.0.1/ 了，直接运行 sparrow 可更新，如果还不行进入cd ~/.sparrow/sparrow-view/   运行 yarn serve 看是否可以运行

**Comment by jtfl2008** [comment]
进入文件下运行项目 node-sass安装失败，安装成功后，项目正常。建议dart-sass，谢谢。

**Comment by eszhang** [comment]
我的也是一样的

**Comment by sparrow-js** [comment]
> 我的也是一样的，手动把sparrow-view 启起来了，但是添加组件的时候提示报错，请问有人解决了么

报错的具体信息是什么？

**Comment by sparrow-js** [comment]
已换成dart-sass

**Comment by eszhang** [comment]
2020-06-01 16:39:05,448 INFO 10476 [egg-view-nunjucks] loading templates from ["C:\\Users\\FH\\.sparrow\\sparrow-server\\dist\\app\\view"]

2020-06-01 16:39:05,904 INFO 10476 home.setting.workFolder

2020-06-01 16:40:44,166 INFO 10476 home.setting.workFolder

2020-06-01 16:40:49,067 ERROR 10476 nodejs.SyntaxError: Unexpected token, expected "{" (1:7)
    at Parser._raise (C:\Users\FH\.sparrow\sparrow-server\node_modules\@babel\parser\lib\index.js:746:17)
    at Parser.raiseWithData (C:\Users\FH\.sparrow\sparrow-server\node_modules\@babel\parser\lib\index.js:739:17)

**Comment by eszhang** [comment]
> > 我的也是一样的，手动把sparrow-view 启起来了，但是添加组件的时候提示报错，请问有人解决了么
> 
> 报错的具体信息是什么？

2020-06-01 16:39:05,448 INFO 10476 [egg-view-nunjucks] loading templates from ["C:\\Users\\FH\\.sparrow\\sparrow-server\\dist\\app\\view"]

2020-06-01 16:39:05,904 INFO 10476 home.setting.workFolder

2020-06-01 16:40:44,166 INFO 10476 home.setting.workFolder

2020-06-01 16:40:49,067 ERROR 10476 nodejs.SyntaxError: Unexpected token, expected "{" (1:7)
    at Parser._raise (C:\Users\FH\.sparrow\sparrow-server\node_modules\@babel\parser\lib\index.js:746:17)
    at Parser.raiseWithData (C:\Users\FH\.sparrow\sparrow-server\node_modules\@babel\parser\lib\index.js:739:17)

**Comment by sparrow-js** [comment]
> > > 我的也是一样的，手动把sparrow-view 启起来了，但是添加组件的时候提示报错，请问有人解决了么
> > 
> > 
> > 报错的具体信息是什么？
> 
> 2020-06-01 16:39:05,448 INFO 10476 [egg-view-nunjucks] loading templates from ["C:\Users\FH\.sparrow\sparrow-server\dist\app\view"]
> 
> 2020-06-01 16:39:05,904 INFO 10476 home.setting.workFolder
> 
> 2020-06-01 16:40:44,166 INFO 10476 home.setting.workFolder
> 
> 2020-06-01 16:40:49,067 ERROR 10476 nodejs.SyntaxError: Unexpected token, expected "{" (1:7)
> at Parser._raise (C:\Users\FH.sparrow\sparrow-server\node_modules@babel\parser\lib\index.js:746:17)
> at Parser.raiseWithData (C:\Users\FH.sparrow\sparrow-server\node_modules@babel\parser\lib\index.js:739:17)

辛苦添加下
1.操作步骤
2.node 版本

**Comment by sparrow-js** [comment]
> > > 我的也是一样的，手动把sparrow-view 启起来了，但是添加组件的时候提示报错，请问有人解决了么
> > 
> > 
> > 报错的具体信息是什么？
> 
> 2020-06-01 16:39:05,448 INFO 10476 [egg-view-nunjucks] loading templates from ["C:\Users\FH\.sparrow\sparrow-server\dist\app\view"]
> 
> 2020-06-01 16:39:05,904 INFO 10476 home.setting.workFolder
> 
> 2020-06-01 16:40:44,166 INFO 10476 home.setting.workFolder
> 
> 2020-06-01 16:40:49,067 ERROR 10476 nodejs.SyntaxError: Unexpected token, expected "{" (1:7)
> at Parser._raise (C:\Users\FH.sparrow\sparrow-server\node_modules@babel\parser\lib\index.js:746:17)
> at Parser.raiseWithData (C:\Users\FH.sparrow\sparrow-server\node_modules@babel\parser\lib\index.js:739:17)

请添加下
1.操作步骤
2.node 版本

**Comment by edagarli** [comment]
改成127.0.0.1还不是一样的问题，  127.0.0.1 拒绝了我们的连接请求。

**Comment by sparrow-js** [comment]
> 改成127.0.0.1还不是一样的问题， 127.0.0.1 拒绝了我们的连接请求。

和127.0.0.1没有关系，服务都是本地启动的，没启动成功可能是本地依赖没有安装成功

**Comment by SinuxLee** [comment]
1. 我的机器上运行，也出现了“127.0.0.1 拒绝了我们的连接请求”。初步看是9000端口的服务没有拉起导致的。  
2. 执行sparrow命令后，vscode会莫名打开“C:\Users\Administrator\.sparrow\sparrow-view\node_modules\@vue\cli-service\bin”，而我的机器上js文件默认打开方式正是vscode。
3. 我的推测可能跟parrow-cli\command\start\index.js中第114行的这句话有关
`execa(path.join(VIEW_PATH, 'node_modules/@vue/cli-service/bin/vue-cli-service.js')`，是不是代码中指定文件打开方式就可以呢，像这样:
`execa('node', path.join(VIEW_PATH, 'node_modules/@vue/cli-service/bin/vue-cli-service.js')`

**Comment by sparrow-js** [comment]
> 1. 我的机器上运行，也出现了“127.0.0.1 拒绝了我们的连接请求”。初步看是9000端口的服务没有拉起导致的。
> 2. 执行sparrow命令后，vscode会莫名打开“C:\Users\Administrator.sparrow\sparrow-view\node_modules@vue\cli-service\bin”，而我的机器上js文件默认打开方式正是vscode。
> 3. 我的推测可能跟parrow-cli\command\start\index.js中第114行的这句话有关
>    `execa(path.join(VIEW_PATH, 'node_modules/@vue/cli-service/bin/vue-cli-service.js')`，是不是代码中指定文件打开方式就可以呢，像这样:
>    `execa('node', path.join(VIEW_PATH, 'node_modules/@vue/cli-service/bin/vue-cli-service.js')`


加上了，升级下sparrow 试试

**Comment by SinuxLee** [comment]
> > 1. 我的机器上运行，也出现了“127.0.0.1 拒绝了我们的连接请求”。初步看是9000端口的服务没有拉起导致的。
> > 2. 执行sparrow命令后，vscode会莫名打开“C:\Users\Administrator.sparrow\sparrow-view\node_modules@vue\cli-service\bin”，而我的机器上js文件默认打开方式正是vscode。
> > 3. 我的推测可能跟parrow-cli\command\start\index.js中第114行的这句话有关
> >    `execa(path.join(VIEW_PATH, 'node_modules/@vue/cli-service/bin/vue-cli-service.js')`，是不是代码中指定文件打开方式就可以呢，像这样:
> >    `execa('node', path.join(VIEW_PATH, 'node_modules/@vue/cli-service/bin/vue-cli-service.js')`
> 
> 加上了，升级下sparrow 试试

赞！我这边运行正常了。

**Comment by Jerrodly** [comment]
> 已换成dart-sass

建议换成less，主要处于性能考虑，sass是需要在基于ruby服务容器环境下运行
