### ISSUE TITLE
本地无法运行

### ISSUE THREAD

**Issue by cryboy007** [sparrow-js/sparrow#21]
报错信息,node 版本为v14.15.0
![image](https://user-images.githubusercontent.com/38103600/99225048-6006f580-2822-11eb-86a6-ceefaa9d2b2a.png)

**Comment by MrLawrenc** [comment]
我也是同样的错，好像9000那个端口没启起来，希望大佬有时间瞅瞅
环境win10 node v14.15.1  
![image](https://user-images.githubusercontent.com/35510822/99869509-8227bb80-2c06-11eb-9eb3-3017b9283df9.png)

**Comment by sparrow-js** [comment]
> 我也是同样的错，好像9000那个端口没启起来，希望大佬有时间瞅瞅
> 环境win10 node v14.15.1
> ![image](https://user-images.githubusercontent.com/35510822/99869509-8227bb80-2c06-11eb-9eb3-3017b9283df9.png)

> 我也是同样的错，好像9000那个端口没启起来，希望大佬有时间瞅瞅
> 环境win10 node v14.15.1
> ![image](https://user-images.githubusercontent.com/35510822/99869509-8227bb80-2c06-11eb-9eb3-3017b9283df9.png)

应该是服务依赖没安装成功，进入cd ~/.sparrow/sparrow-view，手动启动下看看是否报错

**Comment by MrLawrenc** [comment]
> > 我也是同样的错，好像9000那个端口没启起来，希望大佬有时间瞅瞅
> > 环境win10 node v14.15.1
> > ![image](https://user-images.githubusercontent.com/35510822/99869509-8227bb80-2c06-11eb-9eb3-3017b9283df9.png)
> 
> > 我也是同样的错，好像9000那个端口没启起来，希望大佬有时间瞅瞅
> > 环境win10 node v14.15.1
> > ![image](https://user-images.githubusercontent.com/35510822/99869509-8227bb80-2c06-11eb-9eb3-3017b9283df9.png)
> 
> 应该是服务依赖没安装成功，进入cd ~/.sparrow/sparrow-view，手动启动下看看是否报错

谢谢大佬  手动启动可以了

**Comment by cryboy007** [comment]
进入文件夹手动执行,是这个样子..
![image](https://user-images.githubusercontent.com/38103600/99923400-8cfe5f80-2d70-11eb-8317-1362bf46ca4d.png)

**Comment by sparrow-js** [comment]
@cryboy007  你的问题跟这个不一样，我晚点儿看看

**Comment by cryboy007** [comment]
....好吧
