### ISSUE TITLE
公网IP反向代理到内网IP有问题

### ISSUE THREAD

**Issue by w7team** [sparrow-js/sparrow#24]
![image](https://user-images.githubusercontent.com/74588507/101055162-a602de00-35c4-11eb-82a5-4a1b2a7f139b.png)
![image](https://user-images.githubusercontent.com/74588507/101055388-d0549b80-35c4-11eb-89e8-4ca3935c7d98.png)

改进建议：应该根据访问地址来赋值给相关的变量

**Comment by sparrow-js** [comment]
现在这个是按客户端思路实现的，不太适合往服务器部署，需要修改的地方较多，后续会考虑开源适合在服务器上部署的方案
