### ISSUE TITLE
如何链接接口&添加页面

### ISSUE THREAD

**Issue by chaserstrong** [sparrow-js/sparrow#27]
请教下如何连接后端的接口，以及如何自己添加更多的路由页面和路由，以及如何自己新增组件？
@sparrow-js

**Comment by sparrow-js** [comment]
1.如何连接后端的接口：右面数据库形状icon有加接口功能，绑定不太好用，新方案开发中；
2.如何自己添加更多的路由页面和路由：工程化相关筹备中；
3.如何自己新增组件：有插件功能demo在这里，有疑问可这里问或加wechat联系我， https://github.com/sparrow-js/sparrow/tree/master/packages/plugin-demo

后续大致规划：
 1.接口创建、数据绑定；
 2.二次开发；
 3.文档；
 4.工程化相关；
 5.丰富物料；
 6. 等等；
 会大致按照这个顺序开发后续功能

**Comment by sparrow-js** [comment]
> 请教下如何连接后端的接口，以及如何自己添加更多的路由页面和路由，以及如何自己新增组件？
> @sparrow-js

1.如何连接后端的接口：右面数据库形状icon有加接口功能，绑定不太好用，新方案开发中；
2.如何自己添加更多的路由页面和路由：工程化相关筹备中；
3.如何自己新增组件：有插件功能demo在这里，有疑问可这里问或加wechat联系我， https://github.com/sparrow-js/sparrow/tree/master/packages/plugin-demo

后续大致规划：
1.接口创建、数据绑定；
2.二次开发；
3.文档；
4.工程化相关；
5.丰富物料；
6. 等等；
会大致按照这个顺序开发后续功能
