### ISSUE TITLE
线上演示和本地启动都没有任何组件可以添加

### ISSUE THREAD

**Issue by x007xyz** [sparrow-js/sparrow#28]

**Comment by sparrow-js** [comment]
> _No description provided._

线上用的什么浏览器？本地可以看下这个https://github.com/sparrow-js/sparrow/issues/15是否能解决

**Comment by sparrow-js** [comment]
> _No description provided._

线上用的什么浏览器？本地可以看下这个   https://github.com/sparrow-js/sparrow/issues/15   是否能解决

**Comment by sparrow-js** [comment]
> _No description provided._

socket.io 更新影响本地不展示组件，已更新，命令行直接运行sparrow即可
