### ISSUE TITLE
docker容器部署点击源代码，提示打开编辑失败

### ISSUE THREAD

**Issue by woshidafengzi** [sparrow-js/sparrow#30]
<img width="1411" alt="QQ20210127-105415@2x" src="https://user-images.githubusercontent.com/22409098/105936771-42120880-608f-11eb-8e3a-b2fe2bbfce65.png">

**Comment by woshidafengzi** [comment]
打开编辑器失败，请先手动启动编辑器，或者将编辑器注册到终端命令行中

**Comment by sparrow-js** [comment]
> 打开编辑器失败，请先手动启动编辑器，或者将编辑器注册到终端命令行中

编辑器是打开的vscode，代码在～/.sparrow/sparrow-view/src/views/下，打不开可自行在任意编辑器下自行打开
